# Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    honor_labels: true
    metrics_path: "/sampleservice/admin/internal/metrics"
    static_configs:
      - targets: ["host.docker.internal:8080"]